#############################################################################
# Makefile for building: libagileplugin.so.1.0.0
# Generated by qmake (2.01a) (Qt 4.8.6) on: ven. oct. 21 16:59:43 2016
# Project:  agileplugin.pro
# Template: lib
# Command: /usr/lib/x86_64-linux-gnu/qt4/bin/qmake -o Makefile agileplugin.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DGUI_EXPORT= -DCORE_EXPORT= -DQT_XML_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -m64 -pipe -O2 -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -m64 -pipe -std=c++0x -O2 -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtXml -I/usr/include/qt4 -I/usr/include/qgis -Iinclude -Ibuild/.moc
LINK          = g++
LFLAGS        = -m64 -Wl,-O1 -shared -Wl,-soname,libagileplugin.so.1
LIBS          = $(SUBLIBS)  -L/usr/lib/x86_64-linux-gnu -L/usr/lib -lqgis_core -lqgis_gui -lQtXml -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/lib/x86_64-linux-gnu/qt4/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = build/.o/

####### Files

SOURCES       = agileplugin.cpp \
		src/windowLatLng.cpp build/.moc/moc_agileplugin.cpp \
		build/.moc/moc_windowLatLng.cpp
OBJECTS       = build/.o/agileplugin.o \
		build/.o/windowLatLng.o \
		build/.o/moc_agileplugin.o \
		build/.o/moc_windowLatLng.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		agileplugin.pro
QMAKE_TARGET  = agileplugin
DESTDIR       = build/
TARGET        = libagileplugin.so.1.0.0
TARGETA       = build/libagileplugin.a
TARGETD       = libagileplugin.so.1.0.0
TARGET0       = libagileplugin.so
TARGET1       = libagileplugin.so.1
TARGET2       = libagileplugin.so.1.0

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile  build/$(TARGET)

build/$(TARGET):  $(OBJECTS) $(SUBLIBS) $(OBJCOMP)  
	@$(CHK_DIR_EXISTS) build/ || $(MKDIR) build/ 
	-$(DEL_FILE) $(TARGET) $(TARGET0) $(TARGET1) $(TARGET2)
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(LIBS) $(OBJCOMP)
	-ln -s $(TARGET) $(TARGET0)
	-ln -s $(TARGET) $(TARGET1)
	-ln -s $(TARGET) $(TARGET2)
	-$(DEL_FILE) build/$(TARGET)
	-$(DEL_FILE) build/$(TARGET0)
	-$(DEL_FILE) build/$(TARGET1)
	-$(DEL_FILE) build/$(TARGET2)
	-$(MOVE) $(TARGET) $(TARGET0) $(TARGET1) $(TARGET2) build/
	cp build/libagileplugin.so.1.0.0 /usr/lib/qgis/plugins/libagileplugin.so



staticlib: $(TARGETA)

$(TARGETA):  $(OBJECTS) $(OBJCOMP) 
	-$(DEL_FILE) $(TARGETA) 
	$(AR) $(TARGETA) $(OBJECTS)

Makefile: agileplugin.pro  /usr/share/qt4/mkspecs/linux-g++-64/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf
	$(QMAKE) -o Makefile agileplugin.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
qmake:  FORCE
	@$(QMAKE) -o Makefile agileplugin.pro

dist: 
	@$(CHK_DIR_EXISTS) build/.o/agileplugin1.0.0 || $(MKDIR) build/.o/agileplugin1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) build/.o/agileplugin1.0.0/ && $(COPY_FILE) --parents agileplugin.h include/windowLatLng.h build/.o/agileplugin1.0.0/ && $(COPY_FILE) --parents agileplugin.cpp src/windowLatLng.cpp build/.o/agileplugin1.0.0/ && (cd `dirname build/.o/agileplugin1.0.0` && $(TAR) agileplugin1.0.0.tar agileplugin1.0.0 && $(COMPRESS) agileplugin1.0.0.tar) && $(MOVE) `dirname build/.o/agileplugin1.0.0`/agileplugin1.0.0.tar.gz . && $(DEL_FILE) -r build/.o/agileplugin1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) build/$(TARGET) 
	-$(DEL_FILE) build/$(TARGET0) build/$(TARGET1) build/$(TARGET2) $(TARGETA)
	-$(DEL_FILE) Makefile


check: first

/usr/lib/x86_64-linux-gnu/qt4/bin/moc:
	(cd $(QTDIR)/src/tools/moc && $(MAKE))

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: build/.moc/moc_agileplugin.cpp build/.moc/moc_windowLatLng.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) build/.moc/moc_agileplugin.cpp build/.moc/moc_windowLatLng.cpp
build/.moc/moc_agileplugin.cpp: agileplugin.h \
		/usr/lib/x86_64-linux-gnu/qt4/bin/moc
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) agileplugin.h -o build/.moc/moc_agileplugin.cpp

build/.moc/moc_windowLatLng.cpp: include/windowLatLng.h \
		/usr/lib/x86_64-linux-gnu/qt4/bin/moc
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) include/windowLatLng.h -o build/.moc/moc_windowLatLng.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

build/.o/agileplugin.o: agileplugin.cpp agileplugin.h \
		utilitaire.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/.o/agileplugin.o agileplugin.cpp

build/.o/windowLatLng.o: src/windowLatLng.cpp utilitaire.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/.o/windowLatLng.o src/windowLatLng.cpp

build/.o/moc_agileplugin.o: build/.moc/moc_agileplugin.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/.o/moc_agileplugin.o build/.moc/moc_agileplugin.cpp

build/.o/moc_windowLatLng.o: build/.moc/moc_windowLatLng.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/.o/moc_windowLatLng.o build/.moc/moc_windowLatLng.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

